# Generated by Django 5.2.16 on 2026-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_storesettings_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, help_text='e.g. 1L, 1.5L, Pack of 6', max_length=80),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reverted', 'Reverted')], default='completed', max_length=20),
        ),
    ]
