# Generated by Django 5.2.16 on 2026-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_variant_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_logo',
            field=models.ImageField(blank=True, help_text='Store logo shown on receipts', null=True, upload_to='store/'),
        ),
    ]
