# Generated by Django 5.2.16 on 2026-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sale_receipt_number_storesettings_store_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='storesettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='auto_backup_interval_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='google_service_account_json',
            field=models.TextField(blank=True, help_text='Paste Google Service Account credentials.json contents here', null=True),
        ),
    ]
